# Generated by Django 5.2.4 on 2025-09-08 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_phone',
            field=models.CharField(default='08012345678', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_time',
            field=models.DurationField(max_length=100),
        ),
    ]
