# Generated by Django 5.2.4 on 2025-09-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_booking_delivery_name_booking_delivery_phone_and_more'),
    ]

    operations = [
    ]
